W4D3-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end
  
  resources :users, only: [:new, :create, :index, :show]
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

W4D3-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <form style="float: right" action=" <%= cats_url %> " method="get">
      <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">

      <input type="submit" name="home" value="cats">
    </form>
    <% if current_user %>
      <form action=" <%= session_url %> " method="post">
        <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">

        <input type="hidden" name="_method" value="delete">
        <input type="submit" name="logout" value="logout">
      </form>
      </br>
      <h2><%="Hi " + current_user.username if current_user%></h2>
    <% else %>
      <form style="display: inline-block;float: right;" for="signup" action=" <%= new_user_url %> " method="get">
        <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">

        <input id="signup"  type="submit" name="sign up" value="sign up">
      </form>
      <form style="display: inline-block;float: right" for="login" action=" <%= new_session_url %> " method="get">
        <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">

        <input id="login" type="submit" name="login" value="login">
      </form>
    <% end %>

    <%= yield %>
  </body>
</html>